apiVersion: apps/v1
kind: Deployment
metadata:
  name: BikeRent
  labels:
    app: BikeRent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BikeRent
  template:
    metadata:
      labels:
        app: BikeRent
    spec:
      containers:
        - name: BikeRent
          image: username/BikeRent:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5